### PR TITLE
Revert "Update README.md"

### PR DESCRIPTION
**Pull request by Milord-Freeman**

### CODE REVIEW

**Comment by Milord-Freeman** [comment]
@AliceVerner pls merge this

**Comment by AliceVerner** [comment]
@Milord-Freeman ok.

**Comment by Milord-Freeman** [comment]
# oh
## so
### wow
** here ** _we_ ~~can~~ 
**_ use_ **  ~~_markup_~~  !!!

**Comment by Milord-Freeman** [comment]
**or not**

**Pull request merged**
